from httpx import AsyncClient
from sqlalchemy import text

from app.db.session import AsyncSessionLocal
from app.models.team import Category, Team
from app.models.user import User
from tests.conftest import MakeUser, auth


async def ticket(client: AsyncClient, user: User, category: Category) -> str:
    r = await client.post(
        "/api/v1/tickets",
        headers=auth(user),
        json={
            "title": "Analytics sample",
            "description": "Generated by the analytics test.",
            "category_id": str(category.id),
        },
    )
    assert r.status_code == 201, r.text
    return r.json()["id"]


async def set_times(
    ticket_id: str,
    *,
    created_hours_ago: float,
    sla_hours: float,
    resolved_after_hours: float | None = None,
    breached: bool = False,
) -> None:
   
    
    async with AsyncSessionLocal() as db:
        await db.execute(
            text(
                """
                UPDATE tickets SET
                    created_at  = now() - make_interval(secs => :ago * 3600),
                    sla_due_at  = now() - make_interval(secs => :ago * 3600)
                                        + make_interval(secs => :sla * 3600),
                    resolved_at = CASE WHEN CAST(:res AS float) IS NULL THEN NULL
                                  ELSE now() - make_interval(secs => :ago * 3600)
                                             + make_interval(secs => CAST(:res AS float) * 3600)
                                  END,
                    status = CASE WHEN CAST(:res AS float) IS NULL
                                  THEN CAST('open' AS ticket_status)
                                  ELSE CAST('resolved' AS ticket_status) END,
                    sla_breached = :breached
                WHERE id = :id
                """
            ),
            {
                "id": ticket_id,
                "ago": created_hours_ago,
                "sla": sla_hours,
                "res": resolved_after_hours,
                "breached": breached,
            },
        )
        await db.commit()


async def test_team_sla_report(
    client: AsyncClient,
    make_user: MakeUser,
    teams: dict[str, Team],
    categories: dict[str, Category],
) -> None:
    requester = await make_user("requester")
    observer = await make_user("observer")
    async with AsyncSessionLocal() as db:
        db.add(Team(name="Hardware", slug="hardware"))  # a team with NO tickets
        await db.commit()

    net, acc = categories["network"], categories["accounts"]
    # network: solved in 2 h (SLA 4 h) -> in time
    await set_times(await ticket(client, requester, net), created_hours_ago=10, sla_hours=4, resolved_after_hours=2)
    # network: solved in 8 h (SLA 4 h) -> late
    await set_times(await ticket(client, requester, net), created_hours_ago=10, sla_hours=4, resolved_after_hours=8)
    # network: still open, already breached
    await set_times(await ticket(client, requester, net), created_hours_ago=6, sla_hours=4, breached=True)
    # accounts: solved in 1 h (SLA 2 h) -> in time
    await set_times(await ticket(client, requester, acc), created_hours_ago=5, sla_hours=2, resolved_after_hours=1)
    # accounts: 40 days old -> OUTSIDE the 30-day window, must not count
    await set_times(await ticket(client, requester, acc), created_hours_ago=40 * 24, sla_hours=2, resolved_after_hours=9)

    r = await client.get("/api/v1/analytics/teams", headers=auth(observer), params={"days": 30})
    assert r.status_code == 200, r.text
    rows = {row["slug"]: row for row in r.json()}

    accounts, network = rows["accounts"], rows["network"]
    # accounts: 1 ticket, solved in 1 h, in time.
    assert (accounts["created"], accounts["resolved"], accounts["breached"]) == (1, 1, 0)
    assert (accounts["median_hours"], accounts["sla_met_pct"], accounts["share_pct"]) == (1.0, 100.0, 25.0)
    # network: 3 tickets, 2 solved (2 h in time, 8 h late), 1 open + breached.
    assert (network["created"], network["resolved"], network["breached"]) == (3, 2, 1)
    assert network["median_hours"] == 5.0  # median of 2 h and 8 h
    assert network["sla_met_pct"] == 50.0  # 1 of the 2 resolved was in time
    assert network["share_pct"] == 75.0  # 3 of the 4 tickets in the window
    assert (accounts["sla_rank"], network["sla_rank"]) == (1, 2)

    hardware = rows["hardware"]
    assert (hardware["created"], hardware["sla_met_pct"], hardware["sla_rank"]) == (0, None, 3)

    # Ordered by rank: best team first.
    assert [row["slug"] for row in r.json()] == ["accounts", "network", "hardware"]


async def test_only_managers_see_analytics(
    client: AsyncClient, make_user: MakeUser, teams: dict[str, Team]
) -> None:
    for role, expected in [("requester", 403), ("agent", 403), ("observer", 200), ("admin", 200)]:
        user = await make_user(role)
        r = await client.get("/api/v1/analytics/teams", headers=auth(user))
        assert r.status_code == expected, (role, r.text)


async def test_days_must_be_sensible(client: AsyncClient, make_user: MakeUser) -> None:
    admin = await make_user("admin")
    for days in (0, 366):
        r = await client.get("/api/v1/analytics/teams", headers=auth(admin), params={"days": days})
        assert r.status_code == 422, r.text