"""add sessions_valid_from to users

Revision ID: 76cd5b11aeb8
Revises: 8c2461a4f0be
Create Date: 2026-09-23 10:05:20.445708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76cd5b11aeb8'
down_revision: Union[str, Sequence[str], None] = '8c2461a4f0be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_valid_from')
    # ### end Alembic commands ###
